# Model Validation
This notebook features tests to validate the PD model's logic.

In [1]:
import axelrod as axl
from axelrod.action import Action
import copy
from itertools import (zip_longest, 
                      combinations, 
                      combinations_with_replacement)
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pd_exp2
import random
import seaborn as sns
import time

C,D = Action.C, Action.D
action_map={0: D, 1: C}`

### 1. Response probabilities set to 0.5 and initial moves generated randomly --> Avg CC Distribution should be approx. 0.25

In [18]:
# Initialize player parameters (5 per player): 
#     The response probabilities to the preceding round of play (4)
#             ( P(C|CC), P(C|CD), P(C|DC), P(C|DD) )
#         initial: C or D
#             The initial move (1)
six_players = np.ones((6,4))/2
rng = np.random.default_rng(1)  # Change seed for different runs
init_moves = rng.integers(0,2, size=6)

print("6 player response probabilities: \n", six_players)
print("LIST of initial moves: ", init_moves)

start = time.time()
plyrs = []
for i,params in enumerate(six_players):
    pl = axl.MemoryOnePlayer(tuple(params),action_map[init_moves[i]])
    plyrs.append(pl)

# RPST payoff matrix - 3, 1, 0, 5 - classic config is also default
pd1000 = pd_exp2.PdTournament(plyrs, reps=1000)

df1, df2=pd1000.data, pd1000.agg_data
print(f"Tournament took {time.time() - start} seconds")
display(df2[["Avg_CC_Distribution"]])

6 player response probabilities: 
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
LIST of initial moves:  [0 1 1 1 0 0]
Instantiating tournament object with these players:  Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player


Analysing: 100%|██████████| 25/25 [00:00<00:00, 36.68it/s]

Tournament took 48.50939083099365 seconds


Avg_CC_Distribution
1000             0.245754

In [19]:
display(df2)

P1_Avg_Norm_Score  P1_Min_Norm_Score  P2_Avg_Norm_Score  \
1000            2.54081           1.508333           1.992047   

      P2_Min_Norm_Score  P3_Avg_Norm_Score  P3_Min_Norm_Score  \
1000           0.799174           1.966227           0.945455   

      P4_Avg_Norm_Score  P4_Min_Norm_Score  P5_Avg_Norm_Score  \
1000           1.982931           0.833333            2.56756   

      P5_Min_Norm_Score  P6_Avg_Norm_Score  P6_Min_Norm_Score  \
1000           1.410256           2.535876           1.458333   

      Avg_of_PL_Scores  Min_of_PL_Scores  Avg_CC_Distribution  
1000          2.264242          0.799174             0.245754

### 2.Parameters set to 0 --> Player scores and CC distribution are 0

In [16]:
# Initialize player parameters (5 per player): 
#     The response probabilities to the preceding round of play (4)
#             ( P(C|CC), P(C|CD), P(C|DC), P(C|DD) )
#         initial: C or D
#             The initial move (1)
six_players = np.zeros((6,4))
init_moves = np.zeros(6)

print("6 player response probabilities: \n", six_players)
print("LIST of initial moves: ", init_moves)
start = time.time()
plyrs = []
for i,params in enumerate(six_players):
    pl = axl.MemoryOnePlayer(tuple(params),action_map[init_moves[i]])
    plyrs.append(pl)

# RPST payoff matrix - 3, 1, 0, 5 - classic config is also default
pd1 = pd_exp2.PdTournament(plyrs)

df1, df2=pd1.data, pd1.agg_data
print(f"Tournament took {time.time() - start} seconds")
display(df2)

6 player response probabilities: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
LIST of initial moves:  [0. 0. 0. 0. 0. 0.]
Instantiating tournament object with these players:  Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player


Analysing: 100%|██████████| 25/25 [00:00<00:00, 47.05it/s]


Tournament took 37.008366107940674 seconds


P1_Avg_Norm_Score  P1_Min_Norm_Score  P2_Avg_Norm_Score  P2_Min_Norm_Score  \
1                1.0                1.0                1.0                1.0   

   P3_Avg_Norm_Score  P3_Min_Norm_Score  P4_Avg_Norm_Score  P4_Min_Norm_Score  \
1                1.0                1.0                1.0                1.0   

   P5_Avg_Norm_Score  P5_Min_Norm_Score  P6_Avg_Norm_Score  P6_Min_Norm_Score  \
1                1.0                1.0                1.0                1.0   

   Avg_of_PL_Scores  Min_of_PL_Scores  Avg_CC_Distribution  
1               1.0               1.0                  0.0

### 3.Parameters set to 1 --> Player scores are 3 and CC distribution is 1

In [13]:
# Initialize player parameters (5 per player): 
#     The response probabilities to the preceding round of play (4)
#             ( P(C|CC), P(C|CD), P(C|DC), P(C|DD) )
#         initial: C or D
#             The initial move (1)
six_players = np.ones((6,4))
init_moves = np.ones(6)

print("6 player response probabilities: \n", six_players)
print("LIST of initial moves: ", init_moves)
start = time.time()
plyrs = []
for i,params in enumerate(six_players):
    pl = axl.MemoryOnePlayer(tuple(params),action_map[init_moves[i]])
    plyrs.append(pl)

# RPST payoff matrix - 3, 1, 0, 5 - classic config is also default
pd1 = pd_exp2.PdTournament(plyrs)

df1, df2=pd1.data, pd1.agg_data
print(f"Tournament took {time.time() - start} seconds")
display(df2)

6 player response probabilities: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
LIST of initial moves:  [1. 1. 1. 1. 1. 1.]
Instantiating tournament object with these players:  Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player,Generic Memory One Player


Analysing: 100%|██████████| 25/25 [00:00<00:00, 88.55it/s]

Tournament took 34.68714118003845 seconds


P1_Avg_Norm_Score  P1_Min_Norm_Score  P2_Avg_Norm_Score  P2_Min_Norm_Score  \
1                3.0                3.0                3.0                3.0   

   P3_Avg_Norm_Score  P3_Min_Norm_Score  P4_Avg_Norm_Score  P4_Min_Norm_Score  \
1                3.0                3.0                3.0                3.0   

   P5_Avg_Norm_Score  P5_Min_Norm_Score  P6_Avg_Norm_Score  P6_Min_Norm_Score  \
1                3.0                3.0                3.0                3.0   

   Avg_of_PL_Scores  Min_of_PL_Scores  Avg_CC_Distribution  
1               3.0               3.0                  1.0